# Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#
# class TestBaidusearch():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.vars = {}
#
#   def teardown_method(self, method):
#     self.driver.quit()
#
#   def test_baidusearch(self):
#     self.driver.get("https://www.baidu.com/")
#     self.driver.set_window_size(731, 852)
#     self.driver.find_element(By.ID, "kw").click()
#     self.driver.execute_script("window.scrollTo(0,0)")
#     self.driver.find_element(By.ID, "kw").send_keys("测试人社区")
#     time.sleep(2)
#     self.driver.find_element(By.ID, "su").click()
#     assert self.driver.find_element(By.LINK_TEXT, "测试人社区").text == "测试人社区"

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBaidusearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_locators(self):
    self.driver.get("https://www.baidu.com/")

    # ID 定位
    search_box_id = self.driver.find_element(By.ID, "kw")

    # Class Name 定位
    search_box_class = self.driver.find_element(By.CLASS_NAME, "s_ipt")

    # Name 定位
    search_box_name = self.driver.find_element(By.NAME, "wd")

    # Link Text 定位 (适用于链接文本)
    link_text_element = self.driver.find_element(By.LINK_TEXT, "新闻")

    # Partial Link Text 定位 (适用于部分链接文本)
    partial_link_text_element = self.driver.find_element(By.PARTIAL_LINK_TEXT, "新")

    # Tag Name 定位
    tag_name_element = self.driver.find_elements(By.TAG_NAME, "input")  # 返回所有 input 标签

    # CSS Selector 定位
    css_selector_element = self.driver.find_element(By.CSS_SELECTOR, "#kw")

    # XPath 定位
    xpath_element = self.driver.find_element(By.XPATH, "//input[@id='kw']")
    