# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBingdemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bingdemo(self):
    self.driver.get("https://cn.bing.com/?mkt=zh-CN")
    self.driver.set_window_size(731, 852)
    self.driver.find_element(By.ID, "sb_form_q").send_keys("Selenium中文官网")
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, "#search_icon > svg").click()
    self.driver.execute_script("window.scrollTo(0,98)")

    assert self.driver.find_element(By.LINK_TEXT, "Selenium").text == "Selenium"
